name: Build com Cache Customizado

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configuração do Cache Avançado para Maven
      - name: Cache do Repositório Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # A chave muda se o pom.xml mudar ou se rodar em outro SO
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          # Fallback para usar o cache anterior mais próximo se o pom.xml mudou
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build da Aplicação Spring Boot
        run: ./mvnw clean package -DskipTests
