name: Build com Cache Customizado

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "mostrar mascaramento"
        env:
          TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
        run: echo "O token é $TOKEN"